name: Bob The Builder

on:
  push:
    tags:
      - 'v*'
    
jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run dist
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
    - name: Attach Artifact
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/*.zip
        asset_name: MacOS_Standalone.zip
        asset_content_type: application/zip
        