name: Bob The Builder

on:
  workflow_run:
    workflows: [CodeQL, mobsfscan]
    branches: "main"
    
jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run dist
    - name: Create Release
      uses: ncipollo/release-action@v1.11.1
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "/dist/*.zip"
