name: Hawkscan

on:
  push:
    branches: [ "main" ]
    
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0
    - name: Set-Up NPM
      uses: actions/setup-node@v3.5.1
    - name: Install Dependencies
      run: npm ci
    - name: Start Service
      run: (npm run start-sirv&)
    - name: StackHawk Scan
      uses: stackhawk/hawkscan-action@v2.0.0
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}
        codeScanningAlerts: true
        githubToken: ${{ github.token }}