name: Hawkscan

on:
  push:
    branches: 'main'
    
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0
    - name: Start Service
      run: npm run start-sirv
    
  hawkscan:
    needs: prep
    runs-on: ubuntu-latest
    steps:
    - name: StackHawk Scan
      uses: stackhawk/hawkscan-action@v2.0.0
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}
