name: Dister

on:
  push:
    branches: ['main']
    tags: 'v*'
    
jobs:
  dist:
    runs-on: ubuntu-latest
    name: Distribute
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
      - name: Attempt build
        run: npm run dist
      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true
          artifacts: 'dist/*.zip'
