name: Example workflow for Snyk Infrastructure as Code with multiple files
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files:
          - package.json
          - rollup.config.js
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ${{ matrix.files }}
